name: CICD Practice
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs:
  node_installation:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out Current Repository"
        uses: actions/checkout@v4
      - name: "Installing Node JS"
        uses: actions:setup-node@v3
        with:
          node-version: '14'
      - name: "Installing bats"
        uses: npm install -g bats
      - name: "Checking Bats Version"
        uses: bats -v